### PR TITLE
Refactor Neat, Fix Evolve Bugs

### LINKED ISSUE #71: Network.evolve() & Neat.evolve() not mutating network
### Description

Running `network.evolve()` & `Neat.evolve()` both are producing silent failures or not evolving the the network.

### To Reproduce

Using `Node.js v10.15.3` and running the following code, produces the following error.

### Expected behavior

* none of the created networks to throw an error 
* the error value to change

### Additional context

There is a large possibility that a large part of this error is coming from the fact that because the output neurons are no longer mutable and the activation functions thereof default to `sigmoid`, regression output outside of the `(0, 1)` can create huge network training issue - _like experienced here_.

### PR DESCRIPTION
**Pull request by christianechevarria**
Fixes #71 #72

### CODE REVIEW

File: src/neat.js [hunk 1]
```diff
@@ -184,278 +227,251 @@ Neat.prototype = {
...
     } else {
-      for (i = 0; i < this.population.length; i++) {
-        var genome = this.population[i];
-        if (this.clear) genome.clear();
-        genome.score = await this.fitness(genome, this.dataset);
+      for (let i = 0; i < self.population.length; i++) {
+        const genome = self.population[i];
+        if (self.clear) genome.clear();
+        genome.score = await self.fitness(dataset, genome);
+        self.population[i] = genome;
```
Comment (dan-ryan) [inline src/neat.js]: Seems pointless to do.

File: src/neat.js [hunk 2]
```diff
@@ -184,278 +227,251 @@ Neat.prototype = {
...
    *
    * @returns {number} Average fitness of the current population
    */
-  getAverage: function () {
-    if (typeof this.population[this.population.length - 1].score === 'undefined') {
-      this.evaluate();
-    }
+  self.getAverage = function () {
+    if (typeof self.population[self.population.length - 1].score === 'undefined')
+      self.evaluate(); // self.evaluate is an async function
```
Comment (dan-ryan) [inline src/neat.js]: Shouldn't this wait if this is an async method?

File: test/network.js [hunk 3]
```diff
@@ -310,7 +310,7 @@ describe('Networks', function () {
       assert.isBelow(0.9, getActivation([0]), 'LSTM error');
       assert.isBelow(getActivation([0]), 0.1, 'LSTM error');
     });
-    it('GRU XOR', function () {
+    it.skip('GRU XOR', function () {
```
Comment (dan-ryan) [inline test/network.js]: Why are you skipping?

File: src/neat.js [hunk 4]
```diff
@@ -44,131 +46,172 @@ var selection = methods.selection;
...
+        const currentMethod = filtered[Math.floor(Math.random() * filtered.length)]
+        
+        if(currentMethod === methods.mutation.ADD_NODE && genome.nodes.length >= self.maxNodes || currentMethod === methods.mutation.ADD_CONN && genome.connections.length >= self.maxConns || currentMethod === methods.mutation.ADD_GATE && genome.gates.length >= self.maxGates) {
+          success = false
+        } else {
+          success = genome.mutate(currentMethod)
+        }
+        
+        // we're done
+        if(success || !filtered || filtered.length === 0) return
```
Comment (dan-ryan) [inline src/neat.js]: Empty return

File: src/architecture/network.js [hunk 5]
```diff
@@ -1994,159 +1984,163 @@ Neat.prototype = {
...
-  /**
-   * Sorts the population by score
-  */
-  sort: function () {
-    this.population.sort(function (a, b) {
-      return b.score - a.score;
-    });
-  },
+    // Provenance
+    let newPopulation = Array(self.provenance).fill(Network.fromJSON(self.template.toJSON()))
```
[the remark this answers is not in the document]
Comment (christianechevarria) [reply src/architecture/network.js]: Good idea! That could come in really handy 👍 

Opened as an issue: https://github.com/liquidcarrot/carrot/issues/84

File: src/architecture/network.js [hunk 6]
```diff
@@ -1841,145 +1840,136 @@ var selection = methods.selection;
...
-   */
-  getOffspring: function () {
-    var parent1 = this.getParent();
-    var parent2 = this.getParent();
-
-    return Network.crossOver(parent1, parent2, this.equal);
-  },
-
+  self.createPool = function createInitialPopulation (network, popsize) {
+    return Array(popsize).fill(Network.fromJSON({ ...network.toJSON(), score: undefined }))
```
[the remark this answers is not in the document]
Comment (christianechevarria) [reply src/architecture/network.js]: This is more of a handy way to do object composition, basically we're composing the network's JSON representation with score: undefined

For reference:
https://medium.com/javascript-scene/the-hidden-treasures-of-object-composition-60cd89480381

^ there are some more relevant examples nearing the end of the article

File: src/architecture/network.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (luiscarbonell) [reply src/architecture/network.js]: `lodash` has a copy/clone function for deep copying.

File: src/neat.js (hunk 2 above)
Comment (christianechevarria) [reply src/neat.js]: Yep! I'm doing a second round of cleanup on Neat and this is top priority

File: src/architecture/network.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (dan-ryan) [reply src/architecture/network.js]: Interesting. I'll have to look more into this one.
